### PR TITLE
Nice plot & more improvements

### LINKED ISSUE #1: Decent/pretty visualization
What kind of visualization do you want?

The bar charts hardly seem the best way to plot this information. First and foremost because right now you're adding a new bar for every new day, so soon the y-axis will become pretty crowded. Second because you can hardly spot where a bar shows an increase compared to the previous day.

If you want to plot the changes over time a simple line plot seems a straightforward choice to me.

### PR DESCRIPTION
**Pull request by bittremieux**
Several changes:
- Some general code & code style improvements.
- Robust handling of the `track_count.txt` file to compare counts with the previous date. Storing the old `lactos.txt` is no longer required.
- Line plot to show the changes in number of assemblies over time, fixes #1.
- Stop tracking generated files as these don't belong under version control.
- Twitter credentials are extracted to an external config file.

I didn't test the the tweeting as I don't have Twitter credentials available, but I'm reasonably confident everything should work.

### CODE REVIEW

**Comment by swuyts** [comment]
Thanks! Testing out the changes locally on the Raspberry Pi.

Figured out I've got to upgrade Numpy as the function datetime64 did not except 2 arguments yet which got implemented in v 1.7 [, as described here](http://stackoverflow.com/questions/9360512/fetching-the-days-using-numpy-datetime)

**Comment by bittremieux** [comment]
Well, version 1.7 has only been released for almost 4 years. ;)

It might be useful to add a [`requirements.txt`](https://pip.pypa.io/en/stable/user_guide/#requirements-files) with all packages and their versions the script requires to inform potential users.

**Comment by swuyts** [comment]
It seems that my Raspberry Pi has been living in the stone ages. I also need to upgrade pandas (was running v 0.8.0 and current is 0.19.2).

Good idea, will add requirements .txt!

**Comment by swuyts** [comment]
Also, I forgot to mention that updating a python module on my Raspberry pi takes over 1 hour, hence the slow reaction time.

**Pull request merged**
